title: GC.OS | Global Collective for Open Source AI
email: fkiraly@gcos.ai
description: Developing open source AI software owned by you and governed democratically for the benefit of society.

# Root URL of GitHub Pages site
url: "https://gc-os-ai.github.io"
baseurl: ""

# Permalink setting
permalink: /:name

# Collections
collections:
  involvement_opportunities:
    permalink: /:url
  projects:
    ouput: true

# Plugins
plugins:
  - jemoji
